using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using SteamRouteFixer.Services.Common;

namespace SteamRouteFixer.Services.SteamFix
{
    public static class HostsManager
    {
        public const string BlockStart = "# >>> Steam Route Fix >>>";
        public const string BlockEnd = "# <<< Steam Route Fix <<<";

        private static readonly Regex BlockRegex = new(
            $"{Regex.Escape(BlockStart)}.*?{Regex.Escape(BlockEnd)}\\r?\\n?",
            RegexOptions.Singleline | RegexOptions.Compiled
        );

        public static string GetHostsPath()
        {
            string systemRoot = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
            return Path.Combine(systemRoot, "System32", "drivers", "etc", "hosts");
        }

        public static Dictionary<string, string> ReadPinnedBlock(string? path = null)
        {
            string hostsFile = path ?? GetHostsPath();
            var entries = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            try
            {
                if (!File.Exists(hostsFile)) return entries;
                string content = File.ReadAllText(hostsFile, Encoding.UTF8);

                var match = BlockRegex.Match(content);
                if (!match.Success) return entries;

                var lines = match.Value.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var line in lines)
                {
                    string trimmed = line.Trim();
                    if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith("#")) continue;

                    var parts = trimmed.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
                    if (parts.Length >= 2)
                    {
                        string ip = parts[0];
                        string host = parts[1];
                        entries[host] = ip;
                    }
                }
            }
            catch { }

            return entries;
        }

        public static string BackupHostsFile(string? path = null)
        {
            string hostsFile = path ?? GetHostsPath();
            StoragePathManager.EnsureDirectories();

            string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            string backupFileName = $"hosts.backup.{timestamp}";
            string appDataBackup = Path.Combine(StoragePathManager.BackupsDirectory, backupFileName);

            try
            {
                if (File.Exists(hostsFile))
                {
                    File.Copy(hostsFile, appDataBackup, true);
                    // Also copy alongside hosts file
                    string localBackup = Path.Combine(Path.GetDirectoryName(hostsFile)!, backupFileName);
                    try { File.Copy(hostsFile, localBackup, true); } catch { }
                }
            }
            catch { }

            return appDataBackup;
        }

        public static bool WritePinnedBlock(Dictionary<string, string> entries, string? path = null, bool makeBackup = true)
        {
            string hostsFile = path ?? GetHostsPath();

            try
            {
                if (!File.Exists(hostsFile))
                {
                    File.WriteAllText(hostsFile, "", Encoding.UTF8);
                }

                if (makeBackup)
                {
                    BackupHostsFile(hostsFile);
                }

                string content = File.ReadAllText(hostsFile, Encoding.UTF8);
                content = BlockRegex.Replace(content, "");

                if (!string.IsNullOrEmpty(content) && !content.EndsWith("\n"))
                {
                    content += Environment.NewLine;
                }

                if (entries.Count > 0)
                {
                    var sb = new StringBuilder();
                    sb.AppendLine(BlockStart);
                    sb.AppendLine($"# Generated by SteamRouteFixer on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");

                    foreach (var kvp in entries.OrderBy(k => k.Key))
                    {
                        sb.AppendLine($"{kvp.Value,-16} {kvp.Key}");
                    }

                    sb.AppendLine(BlockEnd);
                    content += sb.ToString();
                }

                File.WriteAllText(hostsFile, content, Encoding.UTF8);
                return true;
            }
            catch
            {
                return false;
            }
        }

        public static bool PinHost(string host, string ip, bool makeBackup = true)
        {
            var entries = ReadPinnedBlock();
            entries[host] = ip;
            return WritePinnedBlock(entries, makeBackup: makeBackup);
        }

        public static bool PinMultiple(Dictionary<string, string> pins, bool makeBackup = true)
        {
            var entries = ReadPinnedBlock();
            foreach (var kvp in pins)
            {
                entries[kvp.Key] = kvp.Value;
            }
            return WritePinnedBlock(entries, makeBackup: makeBackup);
        }

        public static bool UnpinHost(string host, bool makeBackup = true)
        {
            var entries = ReadPinnedBlock();
            if (entries.Remove(host))
            {
                return WritePinnedBlock(entries, makeBackup: makeBackup);
            }
            return true;
        }

        public static bool ClearAllPinned(bool makeBackup = true)
        {
            return WritePinnedBlock(new Dictionary<string, string>(), makeBackup: makeBackup);
        }

        public static List<string> GetBackupFiles()
        {
            StoragePathManager.EnsureDirectories();
            if (!Directory.Exists(StoragePathManager.BackupsDirectory)) return new List<string>();

            return Directory.GetFiles(StoragePathManager.BackupsDirectory, "hosts.backup.*")
                            .OrderByDescending(f => File.GetCreationTime(f))
                            .ToList();
        }

        public static bool RestoreBackup(string backupFilePath)
        {
            string hostsFile = GetHostsPath();
            try
            {
                if (File.Exists(backupFilePath))
                {
                    // Backup current before restore
                    BackupHostsFile(hostsFile);
                    File.Copy(backupFilePath, hostsFile, true);
                    return true;
                }
            }
            catch { }
            return false;
        }
    }
}
